In [1]:
import numpy as np
import matplotlib.pyplot as plt 
from mpl_toolkits.mplot3d import Axes3D

In [2]:
array = np.array([10,20,30]) 
print(array)

[10 20 30]


In [3]:
array1= np.array([10,20,30,40,50,60,70,80,90,100])
print(array1.shape)

(10,)


In [4]:
arrayreshape = array1.reshape(2,5) 
print(arrayreshape)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
print("shape: ",arrayreshape.shape) 
print("dimension: ",arrayreshape.ndim) 
print("data type: ",arrayreshape.dtype.name) 
print("size: ",arrayreshape.size)                     
print("type",type(arrayreshape)) 

shape:  (2, 5)
dimension:  2
data type:  int64
size:  10
type <class 'numpy.ndarray'>


In [6]:
array2= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
print(array2)
print(array2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [7]:
zeros= np.zeros((3,4))
zeros[0,0]=5
print(zeros)


[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
np.ones((3,4))
np.empty((4,5))
np.arange(10,50,10)

array([10, 20, 30, 40])

In [9]:
x= np.linspace(0,10,40)
print(x)

[ 0.          0.25641026  0.51282051  0.76923077  1.02564103  1.28205128
  1.53846154  1.79487179  2.05128205  2.30769231  2.56410256  2.82051282
  3.07692308  3.33333333  3.58974359  3.84615385  4.1025641   4.35897436
  4.61538462  4.87179487  5.12820513  5.38461538  5.64102564  5.8974359
  6.15384615  6.41025641  6.66666667  6.92307692  7.17948718  7.43589744
  7.69230769  7.94871795  8.20512821  8.46153846  8.71794872  8.97435897
  9.23076923  9.48717949  9.74358974 10.        ]


In [10]:
a= np.array([10,20,30])
b= np.array([40,50,60]) 
print(a+b) 
print(a-b) 
print(a**2) 


[50 70 90]
[-30 -30 -30]
[100 400 900]


In [11]:
x= np.array([100,200,300,400,500,600,700])
liste = [10,20,30,40]
array = np.array([50,60,70,80])
print(liste)
print(array)



[10, 20, 30, 40]
[50 60 70 80]


In [12]:
d = a.copy()
a= np.array([1000,2000,3000,4000,5000,6000,7000]) 
print(a)

[1000 2000 3000 4000 5000 6000 7000]


In [13]:
y=x

z=x

y[0]=5 
print(x,y,z)

[  5 200 300 400 500 600 700] [  5 200 300 400 500 600 700] [  5 200 300 400 500 600 700]


In [14]:
a= np.array([1000,2000,3000,4000,5000,6000,7000]) 
print(a)
print(a[3])
print(a[2:5])
reverse_array = a[::-1] 
print(reverse_array)


[1000 2000 3000 4000 5000 6000 7000]
4000
[3000 4000 5000]
[7000 6000 5000 4000 3000 2000 1000]


In [15]:
k = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(k)
print(k[1,1]) 
print(k[:,1]) 
print(k[1,:]) 
print(k[1,1:4]) 
print(k[-1,:]) 
print(k[:,-1]) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


In [16]:
array5 = np.array([[10,20],[50,60],[70,80]])
print(array5)

[[10 20]
 [50 60]
 [70 80]]


In [17]:
array5.resize((2,3)) 
print(array5)

[[10 20 50]
 [60 70 80]]
